name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        features: ["", "--no-default-features --features rustls-native"]
    runs-on: "ubuntu-latest"
    container: rust:1.61.0

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build ${{ matrix.features }}

  test:
    strategy:
      matrix:
        features: ["", "--no-default-features --features rustls-native"]
    runs-on: "ubuntu-latest"
    container: rust:1.61.0
    services:
      consul:
        image: consul:1.9.3
        env:
          CONSUL_LOCAL_CONFIG: '{"acl": [{"default_policy": "allow", "enable_token_persistence": true, "enabled": true}], "services": [ {"address": "1.1.1.1", "checks": [], "id": "test-service-1", "name": "test-service", "port": 20001}, {"address": "2.2.2.2", "checks": [], "id": "test-service-2", "name": "test-service", "port": 20002}, {"address": "3.3.3.3", "checks": [], "id": "test-service-3", "name": "test-service", "port": 20003} ]}'

    env:
      CONSUL_HTTP_ADDR: http://consul:8500

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: cargo test ${{ matrix.features }}
