name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: rust:1.52
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
