name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        features: ["", "--no-default-features --features rustls-native"]
    runs-on: "ubuntu-latest"
    container: rust:1.61.0

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build ${{ matrix.features }}

  test:
    strategy:
      matrix:
        features: ["", "--no-default-features --features rustls-native"]
    runs-on: "ubuntu-latest"
    container: rust:1.61.0
    steps:
      - uses: actions/checkout@v2
      - name: Setup Consul docker
        run: docker-compose up -d
      - name: Test
        run: cargo test ${{ matrix.features }}
