name: Main

strategy:
  matrix:
    features: ["", "--no-default-features --features rustls-native"]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: rust:1.52.1

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build ${{ matrix.features }}

  test:
    runs-on: "ubuntu-latest"
    container: rust:1.52.1
    services:
      consul:
        image: consul:1.9.3
    env:
      CONSUL_HTTP_ADDR: http://consul:8500

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: cargo test ${{ matrix.features }}
